# Generated by Django 5.2.9 on 2025-12-24 10:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abonent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abonent_kod', models.CharField(help_text='Telefon raqami yoki shaxsiy kod (unique)', max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Abonent kodi')),
                ('pasport_seriya', models.CharField(help_text='Masalan: AA, AB, AC', max_length=10, verbose_name='Pasport seriyasi')),
                ('pasport_raqam', models.CharField(help_text='7 raqamli pasport raqami', max_length=20, verbose_name='Pasport raqami')),
                ('pinfl', models.CharField(help_text='14 raqamli shaxsiy identifikatsiya raqami', max_length=14, unique=True, validators=[django.core.validators.MinLengthValidator(14), django.core.validators.RegexValidator(message="PINFL faqat 14 ta raqamdan iborat bo'lishi kerak", regex='^\\d{14}$')], verbose_name='PINFL (JShShIR)')),
                ('ism', models.CharField(max_length=100, verbose_name='Ism')),
                ('familiya', models.CharField(max_length=100, verbose_name='Familiya')),
                ('otasining_ismi', models.CharField(blank=True, default='', max_length=100, verbose_name='Otasining ismi')),
                ('tugilgan_sana', models.DateField(verbose_name="Tug'ilgan sana")),
                ('jins', models.CharField(choices=[('erkak', 'Erkak'), ('ayol', 'Ayol')], max_length=10, verbose_name='Jinsi')),
                ('rasm', models.ImageField(help_text='Abonentning rasmi', upload_to='abonent_rasmlar/', verbose_name='Rasm')),
                ('manzil', models.TextField(blank=True, default='', verbose_name='Manzil')),
                ('telefon', models.CharField(blank=True, default='', max_length=20, verbose_name='Telefon raqami')),
                ('yaratilgan_vaqt', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('yangilangan_vaqt', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
            ],
            options={
                'verbose_name': 'Abonent',
                'verbose_name_plural': 'Abonentlar',
                'ordering': ['-id'],
            },
        ),
    ]
