# Generated by Django 5.2.9 on 2025-12-24 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspektor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefon', models.CharField(blank=True, default='', max_length=20, verbose_name='Telefon raqami')),
                ('hudud', models.CharField(blank=True, default='', help_text='Inspektor ishlaydigan hudud', max_length=100, verbose_name='Hudud')),
                ('lavozim', models.CharField(blank=True, default='Inspektor', max_length=100, verbose_name='Lavozimi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('yaratilgan_vaqt', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inspektor_profile', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Inspektor',
                'verbose_name_plural': 'Inspektorlar',
                'ordering': ['-id'],
            },
        ),
    ]
