# Generated by Django 5.2.9 on 2025-12-24 17:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonents', '0002_inspektor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonent',
            name='pinfl',
            field=models.CharField(blank=True, help_text='14 raqamli shaxsiy identifikatsiya raqami (ixtiyoriy)', max_length=14, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="PINFL faqat 14 ta raqamdan iborat bo'lishi kerak", regex='^\\d{14}$')], verbose_name='PINFL (JShShIR)'),
        ),
        migrations.AlterField(
            model_name='abonent',
            name='rasm',
            field=models.ImageField(blank=True, help_text='Abonentning rasmi (ixtiyoriy)', null=True, upload_to='abonent_rasmlar/', verbose_name='Rasm'),
        ),
    ]
