# Generated by Django 5.2.9 on 2025-12-24 17:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonents', '0003_alter_abonent_pinfl_alter_abonent_rasm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonent',
            name='abonent_kod',
            field=models.CharField(blank=True, help_text='Telefon raqami yoki shaxsiy kod (ixtiyoriy)', max_length=50, null=True, unique=True, verbose_name='Abonent kodi'),
        ),
        migrations.AlterField(
            model_name='abonent',
            name='familiya',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Familiya'),
        ),
        migrations.AlterField(
            model_name='abonent',
            name='ism',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ism'),
        ),
        migrations.AlterField(
            model_name='abonent',
            name='jins',
            field=models.CharField(blank=True, choices=[('erkak', 'Erkak'), ('ayol', 'Ayol')], default='', max_length=10, verbose_name='Jinsi'),
        ),
        migrations.AlterField(
            model_name='abonent',
            name='pasport_raqam',
            field=models.CharField(blank=True, default='', help_text='7 raqamli pasport raqami (ixtiyoriy)', max_length=20, verbose_name='Pasport raqami'),
        ),
        migrations.AlterField(
            model_name='abonent',
            name='pinfl',
            field=models.CharField(help_text='14 raqamli shaxsiy identifikatsiya raqami (majburiy)', max_length=14, unique=True, validators=[django.core.validators.MinLengthValidator(14), django.core.validators.RegexValidator(message="PINFL faqat 14 ta raqamdan iborat bo'lishi kerak", regex='^\\d{14}$')], verbose_name='PINFL (JShShIR)'),
        ),
        migrations.AlterField(
            model_name='abonent',
            name='rasm',
            field=models.ImageField(help_text='Abonentning rasmi (majburiy)', upload_to='abonent_rasmlar/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='abonent',
            name='tugilgan_sana',
            field=models.DateField(blank=True, null=True, verbose_name="Tug'ilgan sana"),
        ),
    ]
