# Generated by Django 5.2.9 on 2025-12-25 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonents', '0004_alter_abonent_abonent_kod_alter_abonent_familiya_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mahalla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=150, verbose_name='Mahalla nomi')),
                ('yaratilgan_vaqt', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
            ],
            options={
                'verbose_name': 'Mahalla',
                'verbose_name_plural': 'Mahallalar',
                'ordering': ['tuman', 'nomi'],
            },
        ),
        migrations.CreateModel(
            name='Tuman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100, unique=True, verbose_name='Tuman nomi')),
                ('yaratilgan_vaqt', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
            ],
            options={
                'verbose_name': 'Tuman',
                'verbose_name_plural': 'Tumanlar',
                'ordering': ['nomi'],
            },
        ),
        migrations.RemoveField(
            model_name='inspektor',
            name='hudud',
        ),
        migrations.AddField(
            model_name='abonent',
            name='mahalla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abonentlar', to='abonents.mahalla', verbose_name='Mahalla'),
        ),
        migrations.AddField(
            model_name='inspektor',
            name='mahallalar',
            field=models.ManyToManyField(blank=True, related_name='inspektorlar', to='abonents.mahalla', verbose_name='Mahallalar'),
        ),
        migrations.AddField(
            model_name='mahalla',
            name='tuman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mahallalar', to='abonents.tuman', verbose_name='Tuman'),
        ),
        migrations.AddField(
            model_name='abonent',
            name='tuman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abonentlar', to='abonents.tuman', verbose_name='Tuman'),
        ),
        migrations.AddField(
            model_name='inspektor',
            name='tuman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspektorlar', to='abonents.tuman', verbose_name='Tuman'),
        ),
        migrations.AlterUniqueTogether(
            name='mahalla',
            unique_together={('tuman', 'nomi')},
        ),
    ]
