# Generated by Django 5.2.9 on 2025-12-25 20:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonents', '0005_mahalla_tuman_remove_inspektor_hudud_abonent_mahalla_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abonent',
            name='familiya',
        ),
        migrations.RemoveField(
            model_name='abonent',
            name='ism',
        ),
        migrations.RemoveField(
            model_name='abonent',
            name='jins',
        ),
        migrations.RemoveField(
            model_name='abonent',
            name='manzil',
        ),
        migrations.RemoveField(
            model_name='abonent',
            name='otasining_ismi',
        ),
        migrations.RemoveField(
            model_name='abonent',
            name='pasport_raqam',
        ),
        migrations.RemoveField(
            model_name='abonent',
            name='pasport_seriya',
        ),
        migrations.RemoveField(
            model_name='abonent',
            name='telefon',
        ),
        migrations.RemoveField(
            model_name='abonent',
            name='tugilgan_sana',
        ),
        migrations.AlterField(
            model_name='abonent',
            name='mahalla',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='abonentlar', to='abonents.mahalla', verbose_name='Mahalla'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='abonent',
            name='pinfl',
            field=models.CharField(help_text='14 raqamli shaxsiy identifikatsiya raqami', max_length=14, unique=True, validators=[django.core.validators.MinLengthValidator(14), django.core.validators.RegexValidator(message="JSHIR faqat 14 ta raqamdan iborat bo'lishi kerak", regex='^\\d{14}$')], verbose_name='JSHIR'),
        ),
        migrations.AlterField(
            model_name='abonent',
            name='rasm',
            field=models.ImageField(help_text='Abonentning rasmi', upload_to='abonent_rasmlar/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='abonent',
            name='tuman',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='abonentlar', to='abonents.tuman', verbose_name='Tuman'),
            preserve_default=False,
        ),
    ]
