# Generated by Django 5.2.9 on 2025-12-26 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonents', '0006_remove_abonent_familiya_remove_abonent_ism_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonent',
            name='inspektor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_abonents', to='abonents.inspektor', verbose_name='Kiritgan inspektor'),
        ),
    ]
